image: ros:melodic-robot

cache:
  paths:
  - ccache/

before_script:
- git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
- source ros_gitlab_ci/gitlab-ci.bash >/dev/null

# catkin_lint.
catkin lint:
  stage: build
  image: ros:melodic-ros-core
  before_script:
  - apt update  >/dev/null 2>&1
  - apt install -y python-catkin-lint >/dev/null 2>&1
  script:
  - catkin_lint -W3 .

# catkin_make
catkin_make:
  stage: build
  script:
  - catkin_make

catkin_make tests:
  stage: test
  script:
  - catkin_make run_tests

# catkin tools
catkin_tools:
  stage: build
  script:
  - catkin build --summarize --no-status --force-color

catkin tools_tests:
  stage: test
  script:
  - catkin run_tests --no-status --force-color
